version: 2

updates:
  # Backend (Python / pip)
  - package-ecosystem: "pip"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"

    groups:
      backend-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "@testing-library/react"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"

    groups:
      frontend-production-minor-patch:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      frontend-development-minor-patch:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Backend Docker image
  - package-ecosystem: "docker"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"

    groups:
      backend-docker-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # Frontend Docker image
  - package-ecosystem: "docker"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"

    groups:
      frontend-docker-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
