# Generated by Django 5.0.4 on 2026-07-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin"), ("owner", "Owner")],
                default="member",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin"), ("owner", "Owner")],
                default="member",
                max_length=10,
            ),
        ),
    ]
