name: Validate PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure PR comes from staging
        run: |
          echo "PR source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "Only the staging branch can be merged into main."
            exit 1
          fi

          echo "Valid source branch."
